### ISSUE TITLE
Talk Title: Moving Mouse via Tokio

### ISSUE THREAD

**Issue by TwistingTwists** [rustdelhi/talks#10]
## Talk Title *

Moving Mouse via Tokio 
 
## Summary

Let's move the mouse and learn the nuances of async rust. This will cover 

1. tokio::spawn, tokio::spawn_blocking
2. thread::spawn
3. Sharing state between threads and tokio tasks
4. Starting custom tokio runtime with limited thread

## Time Required *

30 min 

## Link to Slides/Content
Will update soon. 

## About you *

Elixir developer with 2+ years of elixir experience. Recently learning rust.

## Your Availability within the next 2 months *

17 February.

## Contact/Social Handles (Telegram/Email/Twitter/LinkedIn) *
Telegram - https://t.me/linkedin132
Twitter - https://twitter.com/twistin456

## Additional Notes/Comments

Feedback welcome.

**Comment by ditsuke** [comment]
Hi @TwistingTwists, confirming that we can host your talk this Saturday. Please drop more details soon.

**Comment by TwistingTwists** [comment]
Thanks for confirmation! 

More details upcoming! It's cooking.

**Comment by ditsuke** [comment]
Hi @TwistingTwists, we're planning to announce the talks by EOD today or early tomorrow.

**Comment by TwistingTwists** [comment]
https://gist.github.com/TwistingTwists/60a37eff013bb1b278752ba258c751a6

Here is a list of question I will try to answer in the talk. :)

**Comment by TwistingTwists** [comment]
@ditsuke : Updated the proposal for the talk here :) 

Will post the detailed slides / github repo soon .

**Comment by gswebspace** [comment]
@TwistingTwists Confirming that we will be hosting this talk for the meetup on 17th Feb. If you need any assistance, please let us know. Thank you !

**Comment by TwistingTwists** [comment]
https://github.com/TwistingTwists/mousemove/pull/1/commits

Here is the repo link. :)
