### ISSUE TITLE
Talk Title: How rust helped us build a fast and lightweight payments switch

### ISSUE THREAD

**Issue by Narayanbhat166** [rustdelhi/talks#11]
## Talk Title *
Hyperswitch - An open payments switch

## Summary
This talk will be about how hyperswitch leverages features of rust to provide a blazingly fast payments switch experience.

## Time Required *
30 minutes

## Link to Slides/Content
todo!()

## About you *
Software Developer at [@juspay](https://github.com/juspay)
Building [@juspay/hyperswitch](https://github.com/juspay/hyperswitch) for over more than a year now.

## Contact/Social Handles (Telegram/Email/Twitter/LinkedIn) *
Github: https://github.com/Narayanbhat166
Linkedin: https://www.linkedin.com/in/narayan-bhat166/

**Comment by ditsuke** [comment]
Hi @Narayanbhat166, thanks for opening the proposal! We can host your talk this Saturday at our meetup at Amigo Co-working Space, Noida, timed 2:00-5:00PM. Please confirm that this works for.you.

**Comment by Narayanbhat166** [comment]
Yes @ditsuke, that works!

**Comment by ditsuke** [comment]
Hi @Narayanbhat166 let us know of any requirements or assistance you might need. Please join our [community group](https://t.me/rustdelhi) and send me your contact number over Telegram (`@ditsuke`) if possible.

**Comment by gswebspace** [comment]
Thank you @Narayanbhat166 for the excellent talk. Closing this thread for now.
If you would like to give another talk please feel free to open an issue in this repo anytime.

**Comment by gswebspace** [comment]
@Narayanbhat166 We have a meetup coming up on the 15th of December in CP.

If you would like to give a talk on any topic please let me know.

Event Info: https://www.meetup.com/rustdelhi/events/304967731
