### ISSUE TITLE
Talk Title: Soy dev's first foray into Rust

### ISSUE THREAD

**Issue by Maniktherana** [rustdelhi/talks#12]
## Talk Title *
Soy dev's first foray into Rust

## Summary
In this talk, I'll be discussing my journey learning rust as a soy dev. I'll briefly go over my attempts at making a TCP echo server and solving Advent of Code in Rust and gracefully failing. After that, I'll move to a more concrete walkthrough on how to make a Todo app in Tauri.

## Time Required *
30-40 minutes

## Link to Slides/Content
TBA

## About you *
I'm a student with about 2 years of experience making fullstack apps using React, NextJS and Python.

## Your Availability within the next 2 months *
Weekends

## Contact/Social Handles (Telegram/Email/Twitter/LinkedIn) *
https://github.com/Maniktherana
https://twitter.com/ManikMkr
https://www.linkedin.com/in/manik-r-91234824a/

**Comment by gswebspace** [comment]
Hello @Maniktherana ! Will you be ready by this saturday for your talk ?
We have out next meetup at the 16th of Dec in Noida and we would like you to give the talk as well.

Meetup Details: https://www.meetup.com/rustdelhi/events/297652586/

Please confirm as soon as possible, Thank you !

**Comment by Maniktherana** [comment]
@gswebspace Yes I'll be available!

**Comment by gswebspace** [comment]
Thank you @Maniktherana for the excellent talk. Closing this thread for now. If you would like to give another talk please feel free to open another issue in this repo anytime.
