### ISSUE TITLE
Talk Title: Functional Rust

### ISSUE THREAD

**Issue by atamakahere-git** [rustdelhi/talks#13]
## Talk Title *
Functional Rust (Opinionated Idiomatic Rust)

## Summary
* Using functional paradigm in rust to avoid unnecessary code and bugs
* Writing clean and performant code at the same time.

## Time Required *
30-40 mins

## Link to Slides/Content
WIP

## About you *
System Engineer (Rust)  (1+ year)

## Your Availability within the next 2 months *
Fridays and Saturdays

## Contact/Social Handles (Telegram/Email/Twitter/LinkedIn) *
online@atamaka.maskmy.id

## Additional Notes/Comments
Please consider a substitute if I do not make it in time.

**Comment by gswebspace** [comment]
Hello @atamakahere-git ! 

Thanks for your talk proposal. Will you be able to present this talk on the 17th of Feb in Delhi in-person ?

Meetup event link : https://www.meetup.com/rustdelhi/events/298864671/

Let us know about your availability, Thank you !

**Comment by atamakahere-git** [comment]
Hi @gswebspace 
Yes, I am available on 17th!

**Comment by gswebspace** [comment]
Excellent, confirming this talk for the meetup on the 17th Feb. If you need any assistance, please let us know.

Thank you !

**Comment by Vyogami** [comment]
Thanks for the session!
