### ISSUE TITLE
Talk Title: Don't Block, Just Flow: Embracing Asynchronous with Rust Streams

### ISSUE THREAD

**Issue by artech-git** [rustdelhi/talks#15]
## Talk Title *
 "Don't Block, Just Flow: Embracing Asynchronous with Rust Streams"
## Summary

I/O iteration is convenient conventional present within the mind of beginner/young "Rustaceans", Through this talk I will attempt to demonstrate a alternative route for addressing issues which may appears through it. Using async Streams we can solve challenges which can be highly nessecary for mission critical and performant apps not overly dependent on 

How will this talk add value to your coding journey ? 

- Learn about building blocks of Stream.
- Drawback/ benefits of Stream within applications.
- Patterns and recommended Practices.
- Alternative flavors and options available in the ecosystem.
- A live example demonstrating efficacy of streams at scale.

## Time Required *
Roughly about 25 min to at most 40 min.
## Link to Slides/Content
W.I.P E.T.A 1 day.
## About you *
Systems engineer, author
## Your Availability within the next 2 months *
Friday & saturday & sunday.
## Contact/Social Handles (Telegram/Email/Twitter/LinkedIn) *
ar9tech@outlook.com
## Additional Notes/Comments
N/A

**Comment by ditsuke** [comment]
Hi @artech-git, confirming that we can host your talk tomorrow at Rust Delhi #5 at IIT Delhi. Please send in the slides soon and confirm your availability.

**Comment by artech-git** [comment]
Alright I'll be available tomorrow I will publish talk slides by today evening.

**Comment by gswebspace** [comment]
Hello @artech-git ! Will you be available to give this talk at our upcoming meetup on 30th of March ?

Event Details: https://www.meetup.com/rustdelhi/events/299771772/

Let me know if you are interested and we will organize it.

**Comment by artech-git** [comment]
Thanks @gswebspace I will be present for this upcoming talk.

**Comment by gswebspace** [comment]
Thanks ! scheduled on March 30th 2024.

**Comment by Vyogami** [comment]
Thanks for the talk!
