### ISSUE TITLE
Talk Title: Heredity and Evolution

### ISSUE THREAD

**Issue by atamakahere-git** [rustdelhi/talks#17]
## Talk Title *

Heredity and Evolution 

## Summary

Understanding Traits, Generics and lifetime in detail.

## Time Required *

30mins

## Link to Slides/Content
https://codeberg.org/atamakahere/heredity-and-evolution (pvt as of now)

TBA

## About you *

linktr.ee/atamakahere

## Additional Notes/Comments

**Comment by gswebspace** [comment]
Thanks for giving the talk @atamakahere-git ! closing this for now
