### ISSUE TITLE
Talk Title: Porting an SDK from JS to Rust - My Experience

### ISSUE THREAD

**Issue by sathyajithps** [rustdelhi/talks#18]
## Talk Title *
Porting an SDK from JS to Rust - My Experience

## Summary

My experience in porting a JavaScript openid-client sdk to Rust. Plus a bonus story of how we used Rust in production.

## Time Required *

30 Minutes

## Link to Slides/Content

WIP

## About you *

I'm a self-taught developer working at MonoCloud, an Identity as a Service startup based in Delhi. I love tech and am a big fan of systems programming. 

## Your Availability within the next 2 months *

Saturdays and Sundays

## Contact/Social Handles (Telegram/Email/Twitter/LinkedIn) *

sathyajithsps@gmail.com

**Comment by gswebspace** [comment]
@sathyajithps Thanks for showing interest in giving a talk at Rust Delhi. We will be happy to host you on the 24th Aug.

Meetup Details: https://www.meetup.com/rustdelhi/events/302751032/

If you need any help, let me know (Telegram: @gswebspace)

**Comment by sathyajithps** [comment]
Updated time from 15 mins to 30 mins.

**Comment by gswebspace** [comment]
thanks ! noted
