### ISSUE TITLE
Talk Title: Usage of the OWASP DevSecOps Maturity Model

### ISSUE THREAD

**Issue by ptechofficial** [rustdelhi/talks#2]
## Talk Title *
 Usage of the OWASP DevSecOps Maturity Model

## Summary
DSOMM Overview:
DSOMM, the DevSecOps Maturity Model, propels organizations toward robust DevSecOps maturity via structured dimensions and sub-dimensions. It guides enhanced software practices with a security emphasis and offers progress tracking.

Updates and Contributions:
As a Google Summer of Code 2023 contributor, I've advanced DSOMM with Team-Based Assessment and other refinements, enriching its evaluation process.

Organizational Benefits:
DSOMM empowers organizations in heightening software security. Tailored guidance acknowledges diverse paths to DevSecOps maturity. Adhering to DSOMM's framework systematically enhances practices and nurtures a security-centric culture.

DSOMM guides organizations toward DevSecOps maturity, its dimensions and updates drive growth. It underlines security's role in modern software development, fostering excellence in alignment with organizational goals.

The talk is going to be based on Cybersecurity.

## Time Required *
30-45 minutes

## About you *
I am Prakarsh Gupta, a 2023 undergrad from NIT Kurukshetra. Google Summer of Code 2023 contributor to OWASP and SDE1 @ Expedia Group. I have contributed to the DSOMM project of OWASP and I will be giving a brief talk on the contributions I made to the project.

## Your Availability within the next 2 months *
Available only on weekends

## Contact/Social Handles (Telegram/Email/Twitter/LinkedIn) *
[Linkedin](https://www.linkedin.com/in/prakarshgupta/) | [Twitter ](https://twitter.com/prakkarshh)| [Email ](prakarshgupta02051@gmail.com)

## Additional Notes/Comments
I understand that the talk is not related to Rust, however many events allow talks on different topics which is why I am submitting this talk.

**Comment by gswebspace** [comment]
Hi @ptechofficial ! 

Would it be possible to add some Rust code snippets on how to implement various OWASP recommendations ?

A few snippets should be sufficient to make the talk link to rust and then we will be happy to host this talk.

Let me know if that works for you ?

**Comment by ptechofficial** [comment]
Hi @gswebspace,
Since the whole project is based on Typescript and Angular. Also, it only has a  front-end. I am not really sure if I can show any snippets related to Rust in that(reason being rust is used for backend) .

**Comment by gswebspace** [comment]
@ptechofficial I like the idea of the talk and overall support the talk.
We can consider this talk in the next event, likely in September.

I will appreciate mentions of how rust devs can adopt the OWASP model and tips/tricks to get better at security using crates available in rust.

We will circle back to you once a date/venue is confirmed for next month.

**Comment by ptechofficial** [comment]
Sounds Good to me :)

**Comment by gswebspace** [comment]
@ptechofficial Have you managed to update your talk to include Rust in it ? We have an event coming up this Saturday where we need to have rust centric talks.

Let us know if your presentation is ready for an audience of Rust enthusiasts ?

**Comment by gswebspace** [comment]
Closing the thread due to inactivity. Please revive if Rust has been included in the talk.
