### ISSUE TITLE
Talk Title: Smart Pointers

### ISSUE THREAD

**Issue by Blonteractor** [rustdelhi/talks#3]
## Talk Title
Smart Pointers

## Summary 
As the next meetup is going to focus on concurrency I thought it would be nice discuss some primitives for it. I will cover Cell (and UnsafeCell), Box, Rc(and Arc) and RefCell. Maybe NonNull too.

## Time Required
30-45min

## About you 
Hey, I am Priyanshu Verma, currently in my 3rd year of uni. I work with rust as an intern at Aftershoot. Looking to improve my public speaking skills.

## Your Availability within the next 2 months 
I am avaiable on weekends.

## Contact/Social Handles (Telegram/Email/Twitter/LinkedIn) 
[LinkedIn](https://www.linkedin.com/in/blonteractor) | [Twiiter](https://www.twitter.com/blonteractor) | [Email](priyanv2003@gmail.com) 

## Additional Notes/Comments
Hoping to do this one on the 26th :)

**Comment by gswebspace** [comment]
I will likely do an Overview of Concurrency talk and I will briefly allude to smart pointers and won't go into details.

You can cover smart pointers mentioned in detail in your talk.

Overall, looks good to me. Let's do this on the 26th Aug meetup.

cc: @ditsuke

**Comment by gswebspace** [comment]
Thanks @Blonteractor for the amazing talk. I'll close this issue for now. It can be opened again for a future talk if needed.
