### ISSUE TITLE
Talk Title: Many Ways to Concur

### ISSUE THREAD

**Issue by abhin4v** [rustdelhi/talks#5]
## Talk Title

Many Ways to Concur

## Summary

Easy concurrency is one of the main prophesied benefits of the modern functional programming (FP) languages. But the implementation of concurrency differs widely between different FP languages. In this talk, we shall explore the methods and primitives of concurrency across three FP languages: Haskell, Erlang, and Clojure (with core.async).

We shall learn about and compare the trade-offs between:

- the green threads and STM channels oriented concurrency of Haskell
- everything-is-a-process and message-passing actor pattern of Erlang
- macro-based CSP of Clojure/core.async

## Time Required

45 minutes

## Link to Slides/Content

Slides: https://speakerdeck.com/abhin4v/many-ways-to-concur

## About you

Abhinav works as a Senior Software Engineer at Google. Abhinav has worked extensively in Clojure, Go and Java on large distributed systems for past ten years.

He has been dabbling in functional programming for past few years and has been exploring Haskell, Erlang and ML. 

## Your Availability within the next 2 months

Available.

## Contact/Social Handles (Telegram/Email/Twitter/LinkedIn)

Email: abhinav@abhinavsarkar.net
Mastodon: https://fantastic.earth/@abnv
Linkedin: https://linkedin.com/in/abhinavsarkar

**Comment by gswebspace** [comment]
Thanks @abhin4v for the talk proposal ! Happy to host this talk tomorrow.

**Comment by gswebspace** [comment]
Thanks @abhin4v for the amazing talk. I'll close this issue for now. It can be opened again for a future talk if needed.

**Comment by gswebspace** [comment]
@abhin4v We have a meetup coming up on the 15th of December in CP.

If you would like to give a talk on any topic please let me know.

Event Info: https://www.meetup.com/rustdelhi/events/304967731
