### ISSUE TITLE
Talk Title: `serde`: Usage patterns and internals

### ISSUE THREAD

**Issue by MihirLuthra** [rustdelhi/talks#6]
## Talk Title *
`serde`: Usage patterns and internals

## Summary
I am going to talk about:
- Basics of serde
- Usage patterns
- Internals

## Time Required *
30-45 mins

## Link to Slides/Content
TBD

## About you *
Hi, I am MIhir Luthra. I am working as a SDE-3 at Fortanix where I mainly code in Rust.

## Your Availability within the next 2 months *
Available on weekends.

## Contact/Social Handles (Telegram/Email/Twitter/LinkedIn) *
[LinkedIn](https://www.linkedin.com/in/mihir-luthra/)

**Comment by gswebspace** [comment]
@MihirLuthra Thanks for the proposal, it looks good to me. 
We are currently trying to finalize a venue before we can confirm the meetup date/location etc. 

We will reach out to you to discuss your availability as soon as we have the venue finalized.

**Comment by gswebspace** [comment]
@MihirLuthra We will be hosting our next meetup this saturday. 
See: https://www.meetup.com/rustdelhi/events/296654653/

Let us know if that works for you ? or if you have any questions ?

**Comment by MihirLuthra** [comment]
Thanks @gswebspace. That works for me.

**Comment by gswebspace** [comment]
@MihirLuthra 
We have a meetup coming up on the 15th of December in CP.

If you would like to give a talk on any topic please let me know.

Event Info: https://www.meetup.com/rustdelhi/events/304967731
