### ISSUE TITLE
Talk Title: Beneath Rayon: Is Rust's Concurrency Truly Fearless?

### ISSUE THREAD

**Issue by vaibhawvipul** [rustdelhi/talks#8]
## Talk Title *

Beneath Rayon: Is Rust's Concurrency Truly Fearless?

## Summary

We will explore 
- how is rayon library constructed?
- importance of message passing and - std::sync::mpsc crate
- usage of unsafe rust

## Time Required *
30 mins

## About you *
- 6 + years of experience developing distributed databases and HPC. 

## Your Availability within the next 2 months *
- Available in November/December

## Contact/Social Handles (Telegram/Email/Twitter/LinkedIn) *
- [Twitter](https://twitter.com/vaibhaw_vipul)
- [LinkedIn](https://www.linkedin.com/in/vipulvaibhaw/)

**Comment by gswebspace** [comment]
@vaibhawvipul Looks good !

we have a slot for a talk this saturday (14th Oct), would you be interested to give this talk that day ? or should we schedule this for the next event in nov/dec ?

More info: https://www.meetup.com/rustdelhi/events/296654653/

Let us know and we will plan as per your convenience.

**Comment by vaibhawvipul** [comment]
This month won't work unfortunately :) 

I am fine in Nov/Dec.

**Comment by ditsuke** [comment]
Hello @vaibhawvipul, would you like to give your talk at our next meetup scheduled for the 16th of December?

**Comment by gswebspace** [comment]
Hello @vaibhawvipul ! We are organizing another meetup soon on the 17th of Feb. If you would like to give this talk there, let us know ?

Meetup event link: https://www.meetup.com/rustdelhi/events/298864671/

**Comment by gswebspace** [comment]
Hello @vaibhawvipul will you be available on 30th of march for our next meetup https://www.meetup.com/rustdelhi/events/299771772/ ?

**Comment by gswebspace** [comment]
Hello @vaibhawvipul will you be available on the 22nd of June for our next meetup ?

Event Link: https://www.meetup.com/pydelhi/events/301520830/

**Comment by gswebspace** [comment]
@vaibhawvipul Closing this for now. if you want to give a talk next weekend you may reopen this issue.
