### ISSUE TITLE
Talk Title: Drawing Ferris with Inkscape 🦀

### ISSUE THREAD

**Issue by pulsar17** [rustdelhi/talks#9]
## Summary
I'll teach people the basics of vector graphics using [Inkscape](https://inkscape.org). We'll be learning "how to think" while dealing with vector graphics.

We'll make one Ferris 🦀 with the reference from https://rustacean.net/

## Time Required *
30 mins

## Link to Slides/Content
No slides, it's a hands-on session

## About you *
I mostly do Python 🐍
 -   Personal Blog: [https://pulsar17.me/](https://pulsar17.me/)
 -  git{[Hub](https://github.com/pulsar17), [Lab](https://gitlab.com/pulsar17)}
 -  pulsar17 on Telegram
 -  [@pulsar17@mastodon.social](https://mastodon.social/@pulsar17) on Mastodon
 -  [@realpulsar17](https://twitter.com/realpulsar17) on Twitter

## Your Availability within the next 2 months *
14 Oct 2023

## Contact/Social Handles (Telegram/Email/Twitter/LinkedIn) *
Mentioned above

## Additional Notes/Comments
I'll bring Inkscape stickers :)

**Comment by ditsuke** [comment]
Hi Ishaan, confirming this talk can be accommodated at tomorrow's meetup 🦀
